//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RRHH.wsRRHH {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="webServRRHHSoap", Namespace="http://tempuri.org/")]
    public partial class webServRRHH : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getVacantesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPrioridadesRequisitosOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCorrVacOperationCompleted;
        
        private System.Threading.SendOrPostCallback getIdVacOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCapacitacionesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getEmpleadosOperationCompleted;
        
        private System.Threading.SendOrPostCallback getEvaluacionesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUsuariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback getNombresDepartamentosOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDptoIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDptoAbvOperationCompleted;
        
        private System.Threading.SendOrPostCallback validarLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertVacanteOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertRequisitoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public webServRRHH() {
            this.Url = global::RRHH.Properties.Settings.Default.RRHH_wsRRHH_webServRRHH;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getVacantesCompletedEventHandler getVacantesCompleted;
        
        /// <remarks/>
        public event getPrioridadesRequisitosCompletedEventHandler getPrioridadesRequisitosCompleted;
        
        /// <remarks/>
        public event getCorrVacCompletedEventHandler getCorrVacCompleted;
        
        /// <remarks/>
        public event getIdVacCompletedEventHandler getIdVacCompleted;
        
        /// <remarks/>
        public event getCapacitacionesCompletedEventHandler getCapacitacionesCompleted;
        
        /// <remarks/>
        public event getEmpleadosCompletedEventHandler getEmpleadosCompleted;
        
        /// <remarks/>
        public event getEvaluacionesCompletedEventHandler getEvaluacionesCompleted;
        
        /// <remarks/>
        public event getUsuariosCompletedEventHandler getUsuariosCompleted;
        
        /// <remarks/>
        public event getNombresDepartamentosCompletedEventHandler getNombresDepartamentosCompleted;
        
        /// <remarks/>
        public event getDptoIDCompletedEventHandler getDptoIDCompleted;
        
        /// <remarks/>
        public event getDptoAbvCompletedEventHandler getDptoAbvCompleted;
        
        /// <remarks/>
        public event validarLoginCompletedEventHandler validarLoginCompleted;
        
        /// <remarks/>
        public event insertVacanteCompletedEventHandler insertVacanteCompleted;
        
        /// <remarks/>
        public event insertRequisitoCompletedEventHandler insertRequisitoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getVacantes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getVacantes(int top) {
            object[] results = this.Invoke("getVacantes", new object[] {
                        top});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getVacantesAsync(int top) {
            this.getVacantesAsync(top, null);
        }
        
        /// <remarks/>
        public void getVacantesAsync(int top, object userState) {
            if ((this.getVacantesOperationCompleted == null)) {
                this.getVacantesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVacantesOperationCompleted);
            }
            this.InvokeAsync("getVacantes", new object[] {
                        top}, this.getVacantesOperationCompleted, userState);
        }
        
        private void OngetVacantesOperationCompleted(object arg) {
            if ((this.getVacantesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getVacantesCompleted(this, new getVacantesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPrioridadesRequisitos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getPrioridadesRequisitos() {
            object[] results = this.Invoke("getPrioridadesRequisitos", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getPrioridadesRequisitosAsync() {
            this.getPrioridadesRequisitosAsync(null);
        }
        
        /// <remarks/>
        public void getPrioridadesRequisitosAsync(object userState) {
            if ((this.getPrioridadesRequisitosOperationCompleted == null)) {
                this.getPrioridadesRequisitosOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPrioridadesRequisitosOperationCompleted);
            }
            this.InvokeAsync("getPrioridadesRequisitos", new object[0], this.getPrioridadesRequisitosOperationCompleted, userState);
        }
        
        private void OngetPrioridadesRequisitosOperationCompleted(object arg) {
            if ((this.getPrioridadesRequisitosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPrioridadesRequisitosCompleted(this, new getPrioridadesRequisitosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCorrVac", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int getCorrVac(int idDpto) {
            object[] results = this.Invoke("getCorrVac", new object[] {
                        idDpto});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void getCorrVacAsync(int idDpto) {
            this.getCorrVacAsync(idDpto, null);
        }
        
        /// <remarks/>
        public void getCorrVacAsync(int idDpto, object userState) {
            if ((this.getCorrVacOperationCompleted == null)) {
                this.getCorrVacOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCorrVacOperationCompleted);
            }
            this.InvokeAsync("getCorrVac", new object[] {
                        idDpto}, this.getCorrVacOperationCompleted, userState);
        }
        
        private void OngetCorrVacOperationCompleted(object arg) {
            if ((this.getCorrVacCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCorrVacCompleted(this, new getCorrVacCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getIdVac", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int getIdVac(string codVac) {
            object[] results = this.Invoke("getIdVac", new object[] {
                        codVac});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void getIdVacAsync(string codVac) {
            this.getIdVacAsync(codVac, null);
        }
        
        /// <remarks/>
        public void getIdVacAsync(string codVac, object userState) {
            if ((this.getIdVacOperationCompleted == null)) {
                this.getIdVacOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetIdVacOperationCompleted);
            }
            this.InvokeAsync("getIdVac", new object[] {
                        codVac}, this.getIdVacOperationCompleted, userState);
        }
        
        private void OngetIdVacOperationCompleted(object arg) {
            if ((this.getIdVacCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getIdVacCompleted(this, new getIdVacCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCapacitaciones", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getCapacitaciones(int top) {
            object[] results = this.Invoke("getCapacitaciones", new object[] {
                        top});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getCapacitacionesAsync(int top) {
            this.getCapacitacionesAsync(top, null);
        }
        
        /// <remarks/>
        public void getCapacitacionesAsync(int top, object userState) {
            if ((this.getCapacitacionesOperationCompleted == null)) {
                this.getCapacitacionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCapacitacionesOperationCompleted);
            }
            this.InvokeAsync("getCapacitaciones", new object[] {
                        top}, this.getCapacitacionesOperationCompleted, userState);
        }
        
        private void OngetCapacitacionesOperationCompleted(object arg) {
            if ((this.getCapacitacionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCapacitacionesCompleted(this, new getCapacitacionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getEmpleados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getEmpleados() {
            object[] results = this.Invoke("getEmpleados", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getEmpleadosAsync() {
            this.getEmpleadosAsync(null);
        }
        
        /// <remarks/>
        public void getEmpleadosAsync(object userState) {
            if ((this.getEmpleadosOperationCompleted == null)) {
                this.getEmpleadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetEmpleadosOperationCompleted);
            }
            this.InvokeAsync("getEmpleados", new object[0], this.getEmpleadosOperationCompleted, userState);
        }
        
        private void OngetEmpleadosOperationCompleted(object arg) {
            if ((this.getEmpleadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getEmpleadosCompleted(this, new getEmpleadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getEvaluaciones", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getEvaluaciones(int top) {
            object[] results = this.Invoke("getEvaluaciones", new object[] {
                        top});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getEvaluacionesAsync(int top) {
            this.getEvaluacionesAsync(top, null);
        }
        
        /// <remarks/>
        public void getEvaluacionesAsync(int top, object userState) {
            if ((this.getEvaluacionesOperationCompleted == null)) {
                this.getEvaluacionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetEvaluacionesOperationCompleted);
            }
            this.InvokeAsync("getEvaluaciones", new object[] {
                        top}, this.getEvaluacionesOperationCompleted, userState);
        }
        
        private void OngetEvaluacionesOperationCompleted(object arg) {
            if ((this.getEvaluacionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getEvaluacionesCompleted(this, new getEvaluacionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getUsuarios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getUsuarios() {
            object[] results = this.Invoke("getUsuarios", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getUsuariosAsync() {
            this.getUsuariosAsync(null);
        }
        
        /// <remarks/>
        public void getUsuariosAsync(object userState) {
            if ((this.getUsuariosOperationCompleted == null)) {
                this.getUsuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUsuariosOperationCompleted);
            }
            this.InvokeAsync("getUsuarios", new object[0], this.getUsuariosOperationCompleted, userState);
        }
        
        private void OngetUsuariosOperationCompleted(object arg) {
            if ((this.getUsuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUsuariosCompleted(this, new getUsuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getNombresDepartamentos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getNombresDepartamentos() {
            object[] results = this.Invoke("getNombresDepartamentos", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getNombresDepartamentosAsync() {
            this.getNombresDepartamentosAsync(null);
        }
        
        /// <remarks/>
        public void getNombresDepartamentosAsync(object userState) {
            if ((this.getNombresDepartamentosOperationCompleted == null)) {
                this.getNombresDepartamentosOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNombresDepartamentosOperationCompleted);
            }
            this.InvokeAsync("getNombresDepartamentos", new object[0], this.getNombresDepartamentosOperationCompleted, userState);
        }
        
        private void OngetNombresDepartamentosOperationCompleted(object arg) {
            if ((this.getNombresDepartamentosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNombresDepartamentosCompleted(this, new getNombresDepartamentosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getDptoID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int getDptoID(string departamento) {
            object[] results = this.Invoke("getDptoID", new object[] {
                        departamento});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void getDptoIDAsync(string departamento) {
            this.getDptoIDAsync(departamento, null);
        }
        
        /// <remarks/>
        public void getDptoIDAsync(string departamento, object userState) {
            if ((this.getDptoIDOperationCompleted == null)) {
                this.getDptoIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDptoIDOperationCompleted);
            }
            this.InvokeAsync("getDptoID", new object[] {
                        departamento}, this.getDptoIDOperationCompleted, userState);
        }
        
        private void OngetDptoIDOperationCompleted(object arg) {
            if ((this.getDptoIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDptoIDCompleted(this, new getDptoIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getDptoAbv", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getDptoAbv(int idDpto) {
            object[] results = this.Invoke("getDptoAbv", new object[] {
                        idDpto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getDptoAbvAsync(int idDpto) {
            this.getDptoAbvAsync(idDpto, null);
        }
        
        /// <remarks/>
        public void getDptoAbvAsync(int idDpto, object userState) {
            if ((this.getDptoAbvOperationCompleted == null)) {
                this.getDptoAbvOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDptoAbvOperationCompleted);
            }
            this.InvokeAsync("getDptoAbv", new object[] {
                        idDpto}, this.getDptoAbvOperationCompleted, userState);
        }
        
        private void OngetDptoAbvOperationCompleted(object arg) {
            if ((this.getDptoAbvCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDptoAbvCompleted(this, new getDptoAbvCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/validarLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool validarLogin(string user, string clave) {
            object[] results = this.Invoke("validarLogin", new object[] {
                        user,
                        clave});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void validarLoginAsync(string user, string clave) {
            this.validarLoginAsync(user, clave, null);
        }
        
        /// <remarks/>
        public void validarLoginAsync(string user, string clave, object userState) {
            if ((this.validarLoginOperationCompleted == null)) {
                this.validarLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidarLoginOperationCompleted);
            }
            this.InvokeAsync("validarLogin", new object[] {
                        user,
                        clave}, this.validarLoginOperationCompleted, userState);
        }
        
        private void OnvalidarLoginOperationCompleted(object arg) {
            if ((this.validarLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validarLoginCompleted(this, new validarLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertVacante", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void insertVacante(string codVac, string vacante, int idDpto, int cupo, string descripcion) {
            this.Invoke("insertVacante", new object[] {
                        codVac,
                        vacante,
                        idDpto,
                        cupo,
                        descripcion});
        }
        
        /// <remarks/>
        public void insertVacanteAsync(string codVac, string vacante, int idDpto, int cupo, string descripcion) {
            this.insertVacanteAsync(codVac, vacante, idDpto, cupo, descripcion, null);
        }
        
        /// <remarks/>
        public void insertVacanteAsync(string codVac, string vacante, int idDpto, int cupo, string descripcion, object userState) {
            if ((this.insertVacanteOperationCompleted == null)) {
                this.insertVacanteOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertVacanteOperationCompleted);
            }
            this.InvokeAsync("insertVacante", new object[] {
                        codVac,
                        vacante,
                        idDpto,
                        cupo,
                        descripcion}, this.insertVacanteOperationCompleted, userState);
        }
        
        private void OninsertVacanteOperationCompleted(object arg) {
            if ((this.insertVacanteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertVacanteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertRequisito", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void insertRequisito(int idVac, string codVac, string requisito, string detalles, int idPrioridad) {
            this.Invoke("insertRequisito", new object[] {
                        idVac,
                        codVac,
                        requisito,
                        detalles,
                        idPrioridad});
        }
        
        /// <remarks/>
        public void insertRequisitoAsync(int idVac, string codVac, string requisito, string detalles, int idPrioridad) {
            this.insertRequisitoAsync(idVac, codVac, requisito, detalles, idPrioridad, null);
        }
        
        /// <remarks/>
        public void insertRequisitoAsync(int idVac, string codVac, string requisito, string detalles, int idPrioridad, object userState) {
            if ((this.insertRequisitoOperationCompleted == null)) {
                this.insertRequisitoOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertRequisitoOperationCompleted);
            }
            this.InvokeAsync("insertRequisito", new object[] {
                        idVac,
                        codVac,
                        requisito,
                        detalles,
                        idPrioridad}, this.insertRequisitoOperationCompleted, userState);
        }
        
        private void OninsertRequisitoOperationCompleted(object arg) {
            if ((this.insertRequisitoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertRequisitoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getVacantesCompletedEventHandler(object sender, getVacantesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getVacantesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getVacantesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getPrioridadesRequisitosCompletedEventHandler(object sender, getPrioridadesRequisitosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPrioridadesRequisitosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPrioridadesRequisitosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getCorrVacCompletedEventHandler(object sender, getCorrVacCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCorrVacCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCorrVacCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getIdVacCompletedEventHandler(object sender, getIdVacCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getIdVacCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getIdVacCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getCapacitacionesCompletedEventHandler(object sender, getCapacitacionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCapacitacionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCapacitacionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getEmpleadosCompletedEventHandler(object sender, getEmpleadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getEmpleadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getEmpleadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getEvaluacionesCompletedEventHandler(object sender, getEvaluacionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getEvaluacionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getEvaluacionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getUsuariosCompletedEventHandler(object sender, getUsuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUsuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUsuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getNombresDepartamentosCompletedEventHandler(object sender, getNombresDepartamentosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNombresDepartamentosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNombresDepartamentosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getDptoIDCompletedEventHandler(object sender, getDptoIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDptoIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDptoIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getDptoAbvCompletedEventHandler(object sender, getDptoAbvCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDptoAbvCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDptoAbvCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void validarLoginCompletedEventHandler(object sender, validarLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validarLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validarLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void insertVacanteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void insertRequisitoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591